# Generated by Django 4.2.3 on 2023-10-14 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesperson',
            name='img',
            field=models.FileField(default=1, unique='img', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesperson',
            name='phone',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
