# Generated by Django 4.2.3 on 2023-10-17 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0006_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesperson',
            old_name='REGION_CHOICES',
            new_name='region',
        ),
    ]
